apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 4567
    protocol: TCP
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
